### PR TITLE
2016 08 27/postmodernism branch

### LINKED ISSUE #135: errors when trying `lxcfs -h` as a user
Ohai,

```
% ./lxcfs -h
failed to create directory '/run/lxcfs/': Permission deniedFailed to create lxcfs cgroup mountpoint.
Usage:

lxcfs [-p pidfile] mountpoint
  Default pidfile is /run/lxcfs.pid
lxcfs -h
```

Why does lxcfs try to do something while I only wanted to see the help? This is esp annoying as this line is added to the manpage if the build is not running as root :)

### PR DESCRIPTION
**Pull request by brauner**
My first postmodern commit. Closes #135.

### CODE REVIEW

**Comment by brauner** [comment]
I'm unsure how backwards compatible this actually is. Meaning if you have a running instance of `LXCFS` and install a new package including this commit and do a `sudo kill -USR1 $(pidof lxcfs)` this might lead to trouble. A `systemctl restart lxcfs` might be required. Despite that I still like the solution to move the whole cgroup setup code into fuse callbacks.

**Comment by brauner** [comment]
In other words, a `systemctl restart lxcfs` should be done on package upgrade.

**Comment by stgraber** [comment]
@brauner hmm, that'd suck for the stable branch then...

A "systemctl restart lxcfs" breaks all your existing containers, requiring you to restart them all, so not something that'd be suitable for our production users who auto-update to the stable bugfix releases...

**Comment by brauner** [comment]
I fear that if we move anything outside of the `__atttribute(constructor)__` and into `lxcfs.c` then sending `SIGUSR1` to `lxcfs` none of the code we moved into `lxcfs.c` will be re-executed.

**Comment by brauner** [comment]
*Maybe* we can fiddle with `do_reload()`?

**Comment by stgraber** [comment]
@hallyn knows all that stuff much better than I do.

The plan is really that the main C binary be as small as possible, with as little logic as possible. We want bugs and potential security problems to be in the library since that's what we can reload at will without breaking our users.

**Comment by brauner** [comment]
Hm, then I'd argue that we would probably be off best if we leave everything in the constructor even if it isn't the nicest option. Unless @hallyn has a better idea. Moving stuff into `lxcfs.c` isn't so nice anyway since this means we would either have to fuzz around with global variables in a shared library which is not really nice imho  (Especially if you want to keep a consistent view accross all users.) or pass the data around via `fuse`'s `privat_data` but then we still face the problem that anything we mount/setup in `lxcfs.c` can't be reloaded.

**Comment by hallyn** [comment]
Does tests/test_reload.sh pass with this?

**Comment by brauner** [comment]
On Sat, Aug 27, 2016 at 08:51:17PM -0700, Serge Hallyn wrote:
> Does tests/test_reload.sh pass with this?

Sure, it passes. But I think that's also not the problem. The problem ist that
because the setup is now done in lxcfs.c in dedicated fuse lxcfs_init() and
lxcfs_destroy() functions the data (fds, controllers) these two functions
collect and which is needed for the shared library to work after the reload will
*not* be initialized and sent since fuse isn't reloaded. That means when you
simply send SIGUSR1 to lxcfs, then yes, the library will be correctly reloaded
but the cgroup mounts will be busted aka /var/lib/lxcfs/cgroup will not be
correctly setup.

**Comment by brauner** [comment]
Fwiw, we also might get around the problem by not linking `lxcfs` against `liblxcfs`. This way the constructor won't be run before `main`. Rather it would be run, when we first call `dlopen`.

**Comment by brauner** [comment]
Closing in favor of #138.

**Pull request closed without merging**
