### PR TITLE
configure.ac: create symbolic links to config/init/*/lxcfs* files in the build directory 

### PR DESCRIPTION
**Pull request by kllk2320**
Building lxcfs in a directory that is different from the source directory would fail at the installation phase 
because make couldn't find files "config/init/_/lxcfs_" in the build folder. 

Signed-off-by: Liu Kui kllk2320@gmail.com

### CODE REVIEW

**Comment by hallyn** [comment]
Hi,

thanks for the report and the patch.  I'm not sure this fix is right however.  First, 'make distcheck'  still fails this way, because now the 'install lxcfs.service' is trying to overwrite itself.  Secondly, the link feature seems to be about choosing different source files depending on build conditions.

I was hoping that something like:

```
diff --git a/config/init/systemd/Makefile.am b/config/init/systemd/Makefile.am
index 79e96f5..bc74b15 100644
--- a/config/init/systemd/Makefile.am
+++ b/config/init/systemd/Makefile.am
@@ -5,7 +5,7 @@ SYSTEMD_UNIT_DIR = /lib/systemd/system

 install-systemd: lxcfs.service
        $(MKDIR_P) $(DESTDIR)$(SYSTEMD_UNIT_DIR)
-       $(INSTALL_DATA) lxcfs.service $(DESTDIR)$(SYSTEMD_UNIT_DIR)/
+       $(INSTALL_DATA) $(top_srcdir)/config/init/systemd/lxcfs.service $(DESTDIR)$(SYSTEMD_UNIT_DIR)/

 uninstall-systemd:
        rm -f $(DESTDIR)$(SYSTEMD_UNIT_DIR)/lxcfs.service
```

would work, but it also did not suffice to pass make distcheck.

**Comment by kllk2320** [comment]
Hi, hallyn

Yes, you were correct, my fix seems not to be right, as it brings new problem to in-source-tree build, though it solves the problem in out-source-tree build. In comparison, your fix is much more appropriate except that I would prefer to use "abs_srcdir" instead of "top_srcdir" like :
```
diff --git a/config/init/systemd/Makefile.am b/config/init/systemd/Makefile.am
index 79e96f5..d3aaf18 100644
--- a/config/init/systemd/Makefile.am
+++ b/config/init/systemd/Makefile.am
@@ -5,7 +5,7 @@ SYSTEMD_UNIT_DIR = /lib/systemd/system
 
 install-systemd: lxcfs.service
 	$(MKDIR_P) $(DESTDIR)$(SYSTEMD_UNIT_DIR)
-	$(INSTALL_DATA) lxcfs.service $(DESTDIR)$(SYSTEMD_UNIT_DIR)/
+	$(INSTALL_DATA) $(abs_srcdir)/lxcfs.service $(DESTDIR)$(SYSTEMD_UNIT_DIR)/
 
 uninstall-systemd:
 	rm -f $(DESTDIR)$(SYSTEMD_UNIT_DIR)/lxcfs.service
```
As for the reason why make distcheck failed was because it failed at trying to run make distclean, of which the culprit i believe is the 'distclean' target in the top level Makefile.am. The user-defined distclean overrides automake default distclean target which does some clean work that however isn't done by the user-defined distclean.  To fix this, I propose a solution like
```
diff --git a/Makefile.am b/Makefile.am
index bd2604a..5b42dd2 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -66,30 +66,28 @@ endif
 
 tests: TEST_READ TEST_CPUSET TEST_SYSCALLS
 
-distclean:
-       rm -rf .deps/ \
-               INSTALL \
-               Makefile \
-               Makefile.in \
-               aclocal.m4 \
-               autom4te.cache/ \
-               compile \
-               config.guess \
-               config.h \
-               config.h.in \
-               config.log \
-               config.status \
-               config.sub \
-               configure \
-               depcomp \
-               install-sh \
-               libtool \
-               ltmain.sh \
-               lxcfs \
-               lxcfs.1 \
-               lxcfs.o \
-               m4/ \
-               missing \
-               stamp-h1 \
-               tests/test_syscalls \
-               *.lo *.la
+DISTCLEANFILES = INSTALL \
+            Makefile.in \
+            aclocal.m4 \
+            compile \
+            config.guess \
+            config.h.in \
+            config.sub \
+            config/Makefile.in \
+            config/init/Makefile.in \
+            config/init/systemd/Makefile.in \
+            config/init/sysvinit/Makefile.in \
+            config/init/upstart/Makefile.in \
+            configure \
+            depcomp \
+            install-sh \
+            ltmain.sh \
+            m4/libtool.m4 \
+            m4/ltoptions.m4 \
+            m4/ltsugar.m4 \
+            m4/ltversion.m4 \
+            m4/lt~obsolete.m4 \
+            missing \
+            share/Makefile.in \
+            tests/Makefile.in 
+
```
BTW, the file m4/acinclude.m4 shouldn't be cleaned by distclean right?

**Comment by hallyn** [comment]
On Sat, Sep 10, 2016 at 08:51:25AM -0700, Liu Kui wrote:
> Hi, hallyn
> 
> Yes, you were correct, my fix seems not to be right, as it brings new problem to in-source-tree build, though it solves the problem in out-source-tree build. In comparison, your fix is much more appropriate except that I would prefer to use "abs_srcdir" instead of "top_srcdir" like :
> ```
> diff --git a/config/init/systemd/Makefile.am b/config/init/systemd/Makefile.am
> index 79e96f5..d3aaf18 100644
> --- a/config/init/systemd/Makefile.am
> +++ b/config/init/systemd/Makefile.am
> @@ -5,7 +5,7 @@ SYSTEMD_UNIT_DIR = /lib/systemd/system
>  
>  install-systemd: lxcfs.service
>  	$(MKDIR_P) $(DESTDIR)$(SYSTEMD_UNIT_DIR)
> -	$(INSTALL_DATA) lxcfs.service $(DESTDIR)$(SYSTEMD_UNIT_DIR)/
> +	$(INSTALL_DATA) $(abs_srcdir)/lxcfs.service $(DESTDIR)$(SYSTEMD_UNIT_DIR)/
>  
>  uninstall-systemd:
>  	rm -f $(DESTDIR)$(SYSTEMD_UNIT_DIR)/lxcfs.service
> ```

Sounds good - do you mind updating your PR?

> As for the reason why make distcheck failed was because it failed at trying to run make distclean, of which the culprit i believe is the 'distclean' target in the top level Makefile.am. The user-defined distclean overrides automake default distclean target which does some clean work that however isn't done by the user-defined distclean.  To fix this, I propose a solution like
> ```
> diff --git a/Makefile.am b/Makefile.am
> index bd2604a..5b42dd2 100644
> --- a/Makefile.am
> +++ b/Makefile.am
> @@ -66,30 +66,28 @@ endif
>  
>  tests: TEST_READ TEST_CPUSET TEST_SYSCALLS
>  
> -distclean:
> -       rm -rf .deps/ \
> -               INSTALL \
> -               Makefile \
> -               Makefile.in \
> -               aclocal.m4 \
> -               autom4te.cache/ \
> -               compile \
> -               config.guess \
> -               config.h \
> -               config.h.in \
> -               config.log \
> -               config.status \
> -               config.sub \
> -               configure \
> -               depcomp \
> -               install-sh \
> -               libtool \
> -               ltmain.sh \
> -               lxcfs \
> -               lxcfs.1 \
> -               lxcfs.o \
> -               m4/ \
> -               missing \
> -               stamp-h1 \
> -               tests/test_syscalls \
> -               *.lo *.la
> +DISTCLEANFILES = INSTALL \
> +            Makefile.in \
> +            aclocal.m4 \
> +            compile \
> +            config.guess \
> +            config.h.in \
> +            config.sub \
> +            config/Makefile.in \
> +            config/init/Makefile.in \
> +            config/init/systemd/Makefile.in \
> +            config/init/sysvinit/Makefile.in \
> +            config/init/upstart/Makefile.in \
> +            configure \
> +            depcomp \
> +            install-sh \
> +            ltmain.sh \
> +            m4/libtool.m4 \
> +            m4/ltoptions.m4 \
> +            m4/ltsugar.m4 \
> +            m4/ltversion.m4 \
> +            m4/lt~obsolete.m4 \
> +            missing \
> +            share/Makefile.in \
> +            tests/Makefile.in 
> +
> ```

Awesome, thanks.  Do you mind making that a second patch in your PR?

> BTW, the file m4/acinclude.m4 shouldn't be cleaned by distclean right?  

Probably not.

**Comment by kllk2320** [comment]
A change to 'config/init/systemd/Makefile.am' is also needed to pass make distcheck, which i didn't realize until when i run make distcheck on Ubuntu.  Here is the change i made after some thoughts.

```
diff --git a/config/init/systemd/Makefile.am b/config/init/systemd/Makefile.am
index d3aaf18..a6d5d38 100644
--- a/config/init/systemd/Makefile.am
+++ b/config/init/systemd/Makefile.am
@@ -1,7 +1,7 @@
 EXTRA_DIST = lxcfs.service
 
 if INIT_SCRIPT_SYSTEMD
-SYSTEMD_UNIT_DIR = /lib/systemd/system
+SYSTEMD_UNIT_DIR = $(libdir)/systemd/system
 
 install-systemd: lxcfs.service
        $(MKDIR_P) $(DESTDIR)$(SYSTEMD_UNIT_DIR)
```  
I'm still not sure whether using 'libdir' is a proper way, but i couldn't figure a better choice.

**Comment by hallyn** [comment]
I think using libdir is fine.

**Comment by kllk2320** [comment]
Hi, hallyn

FYI, I had already updated the PR as suggested in last commits. Now that the PR is still open ,  I'm not sure if there is anything else to do, can you please take a look at the commits? Thanks.

**Comment by hallyn** [comment]
Hi,

you can't put lib/systemd under $libdir because on ubuntu that ends up building it in $destdir/usr/lib/x86_64-linux-gnu/systemd instea dof $destdir/lib/systemd/

**Comment by stgraber** [comment]
(Closing due to inactivity)

**Pull request closed without merging**
