### PR TITLE
fix 0.0 pcpu issue for ps command

### PR DESCRIPTION
**Pull request by borgerli**
fix issue #444 

Signed-off-by: LI Bo borgerli@tencent.com

### CODE REVIEW

**Comment by brauner** [comment]
Oh wow, I didn't get notifed about this at all. I'm sorry.

**Comment by brauner** [comment]
Can you please sign-off you commit? :)

**Comment by borgerli** [comment]
Oh, I see. Thanks

> Can you please sign-off you commit? :)

**Comment by borgerli** [comment]
Signed-off-by: LI Bo borgerli@tencent.com

**Comment by borgerli** [comment]
@brauner, I signed off this PR. Could you please help review?  Thanks.

**Comment by stgraber** [comment]
@brauner can you take a look?

**Review by brauner — COMMENTED** [review]
I've reviewed this a while ago but I'm not too happy with this approach. The fix here means we're special-casing `ps` which I think is wrong. I would like to understand the root cause of this as this may easily happen with other tools too and we can't keep growing a list of psecial-cased tools. :)

**Comment by borgerli** [comment]
Yes, this PR just fixes a special case. Looking forward to a general solution for such cases. Thanks.

**Pull request closed without merging**
