### PR TITLE
init: respect --prefix when installing systemd unit files

### PR DESCRIPTION
**Pull request by tych0**
Signed-off-by: Tycho Andersen <tycho@tycho.pizza>

### CODE REVIEW

**Comment by tych0** [comment]
Hmm. Actually this isn't quite what I want, but e.g. the sysconfdirs have `--prefix` in them, so maybe we want this? Dunno.

**Review by stgraber — APPROVED** [review]

**Comment by thmo** [comment]
I think this is wrong. lxcfs-5.0.3 installs the service file to  `DESTDIR/usr/usr/lib/systemd/system/lxcfs.service`. Note the double `/usr` in there.

Can we revert that?

**Comment by tych0** [comment]
Fine with me.

**Comment by thmo** [comment]
@stgraber ?

**Pull request merged**
