### PR TITLE
proc_fuse: more swap tweaks

### PR DESCRIPTION
**Pull request by brauner**
Essentially, we stop being clever. This is just a nightmare.

Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
@tomponline, try again.

**Comment by tomponline** [comment]
@brauner seems stable, but output is unexpected:

```
root@test1:~# while :; do date; free -m; sleep 1; done
Tue  9 Jun 13:43:04 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          39         449           0          23         472
Swap:          1024          62         961
```

Shows 62MB swap used.

**Comment by brauner** [comment]
And you're saying no swap is used?

**Comment by tomponline** [comment]
@brauner well it does appear that some swap is being used, although that is unexpected in itself:

Inside container:
```
cat /sys/fs/cgroup/memory/memory.memsw.max_usage_in_bytes
39686144

free -m
              total        used        free      shared  buff/cache   available
Mem:           1024          35         988           0           0         988
```

Is this the right file to be looking at swap usage without relying on lxcfs?

So that looks right. Although I've upped the memory to 1GB, and my host system has 1.3GB free memory:

```
free -m
              total        used        free      shared  buff/cache   available
Mem:           7936        4260        1329         454        2346        2923
Swap:          2047         174        1873
```

So didn't expect this tiny container to use any swap.

I've also tried setting swappiness which didn't change anything:

```
sysctl vm.swappiness = 1
```

**Comment by tomponline** [comment]
@brauner it just seems to be reporting memory usage as swap usage.

**Comment by stgraber** [comment]
@tomponline swap usage is: memsw.usage_in_bytes - usage_in_bytes

**Comment by tomponline** [comment]
```
cat /sys/fs/cgroup/memory/memory.memsw.usage_in_bytes 
37969920
```

So its apparently correct, but very odd that 100% of the container's 35MB of memory is apparently in swap.

```
free -m
              total        used        free      shared  buff/cache   available
Mem:           1024          36         987           0           0         987
Swap:          1024          36         987
```

**Comment by stgraber** [comment]
No, you didn't read me well, you need to substract usage_in_bytes from memsw.usage_in_bytes

**Comment by tomponline** [comment]
@stgraber ah indeed, sorry.

```
root@test1:~# cat /sys/fs/cgroup/memory/memory.usage_in_bytes 
39919616
root@test1:~# cat /sys/fs/cgroup/memory/memory.memsw.usage_in_bytes
39788544
```
So basically 100%.

**Comment by tomponline** [comment]
@stgraber @brauner or is that rather than approximately no swap is in use, as total usage of memory and swap is the same as memory usage?

**Comment by brauner** [comment]
@tomponline, try again.

**Comment by brauner** [comment]
(Accidently closed.)

**Comment by tomponline** [comment]
@brauner now showing 100% usage:

```
root@test1:~# free -m
              total        used        free      shared  buff/cache   available
Mem:            512          37         465           0           8         474
Swap:           512         512           0
root@test1:~# cat /sys/fs/cgroup/memory/memory.memsw.usage_in_bytes
48619520
root@test1:~# cat /sys/fs/cgroup/memory/memory.memsw.usage_in_bytes
48623616
```

**Comment by brauner** [comment]
Can you make sure the commit hash from this branch and the one you built are identical?

**Comment by brauner** [comment]
> @brauner now showing 100% usage:
> 
> ```
> root@test1:~# free -m
>               total        used        free      shared  buff/cache   available
> Mem:            512          37         465           0           8         474
> Swap:           512         512           0
> cat /sys/fs/cgroup/memory/memory.usage_in_bytes 
> 48627712
> cat /sys/fs/cgroup/memory/memory.memsw.usage_in_bytes
> 48619520
> ```

I also need memsw.limit_in_bytes and memory.limit_in_bytes, please.

**Comment by tomponline** [comment]
```
git hash: a2bf61d
make clean
make
sudo make install

sudo -i
root@user-MS-7821:~# lxc-stop test1
root@user-MS-7821:~# systemctl daemon-reload
root@user-MS-7821:~# systemctl stop lxcfs
root@user-MS-7821:~# systemctl start lxcfs
root@user-MS-7821:~# ps aux | grep lxcfs
root      705178  0.0  0.0 151108  1732 ?        Ssl  15:31   0:00 /usr/bin/lxcfs /usr/var/lib/lxcfs
root      705185  0.0  0.0  17536  2664 pts/2    S+   15:31   0:00 grep --color=auto lxcfs
root@user-MS-7821:~# ls -lat /usr/bin/lxcfs
-rwxr-xr-x 1 root root 102328 Jun  9 15:31 /usr/bin/lxcfs
root@user-MS-7821:~# ls -lat /usr/lib/lxcfs/*
-rwxr-xr-x 1 root root    939 Jun  9 15:31 /usr/lib/lxcfs/liblxcfs.la
-rwxr-xr-x 1 root root 752528 Jun  9 15:31 /usr/lib/lxcfs/liblxcfs.so
root@user-MS-7821:~# lxc-start test1
root@user-MS-7821:~# lxc-attach test1
root@test1:~# free -m
              total        used        free      shared  buff/cache   available
Mem:            512          35         476           0           0         476
Swap:           512         512           0
root@test1:~# cat /sys/fs/cgroup/memory/memory.memsw.usage_in_bytes
37597184
root@test1:~# cat /sys/fs/cgroup/memory/memory.usage_in_bytes 
37867520
root@test1:~# cat /sys/fs/cgroup/memory/memory.memsw.limit_in_bytes 
1073741824
root@test1:~# cat /sys/fs/cgroup/memory/memory.limit_in_bytes 
536870912
```

**Comment by brauner** [comment]
@tomponline, try again, please.

**Comment by tomponline** [comment]
@brauner fluctuating between 100% and 0% swap usage:

```
Tue  9 Jun 15:41:32 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          37         468           0           5         474
Swap:           512         512           0
Tue  9 Jun 15:41:33 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          37         468           0           5         474
Swap:             0           0           0
```

```
root@test1:~# cat /sys/fs/cgroup/memory/memory.memsw.usage_in_bytes
45015040
root@test1:~# cat /sys/fs/cgroup/memory/memory.usage_in_bytes
45084672
root@test1:~# cat /sys/fs/cgroup/memory/memory.memsw.limit_in_bytes 
1073741824
root@test1:~# cat /sys/fs/cgroup/memory/memory.limit_in_bytes 
536870912
```

**Comment by brauner** [comment]
@tomponline, try again, please.

**Comment by tomponline** [comment]
@brauner free swap is showing large value now:

```
Tue  9 Jun 15:55:32 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          37         468           0           6         474
Swap:           512         512           0
Tue  9 Jun 15:55:33 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          37         468           0           6         474
Swap:           512         512 18014398509481984
```

**Comment by brauner** [comment]
of course it does.

**Comment by brauner** [comment]
@tomponline, try again, please.

**Comment by tomponline** [comment]
@brauner fluctuating between 100% and 0% used & free:

git hash feb60bf

```
Tue  9 Jun 16:44:08 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          38         454           0          19         473
Swap:           512           0         512
Tue  9 Jun 16:44:09 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          38         453           0          19         473
Swap:           512         512           0
```

**Comment by brauner** [comment]
What does /proc/swaps show for you?
And can you also show /proc/meminfo?
(both in container)

**Comment by brauner** [comment]
@tomponline, try again?

**Comment by tomponline** [comment]
@brauner here you go, I wrote a little script to output all the stuff on a loop:

```
------------------------------------
Tue  9 Jun 17:52:14 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          43         399           0          68         468
Swap:           512         512           0
memory.memsw.limit_in_bytes: 1073741824
memory.memsw.usage_in_bytes: 117436416
memory.limit_in_bytes: 536870912
memory.usage_in_bytes: 117452800
/proc/swaps:
Filename				Type		Size	Used	Priority
none                                    virtual		524288	0	0
/proc/meminfo:
MemTotal:         524288 kB
MemFree:          409576 kB
MemAvailable:     479912 kB
Buffers:               0 kB
Cached:            70336 kB
SwapCached:            0 kB
Active:            39468 kB
Inactive:          50952 kB
Active(anon):      20196 kB
Inactive(anon):      132 kB
Active(file):      19272 kB
Inactive(file):    50820 kB
Unevictable:           0 kB
Mlocked:           75696 kB
SwapTotal:        524288 kB
SwapFree:              0 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:         20220 kB
Mapped:            41316 kB
Shmem:               108 kB
KReclaimable:     124288 kB
Slab:               0 kB
SReclaimable:          0 kB
SUnreclaim:            0 kB
KernelStack:       14656 kB
PageTables:        31676 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6160460 kB
Committed_AS:    7090516 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       96076 kB
VmallocChunk:          0 kB
Percpu:             5920 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      446808 kB
DirectMap2M:     6801408 kB
DirectMap1G:     1048576 kB
              total        used        free      shared  buff/cache   available
Mem:            512          42         400           0          68         469
Swap:           512         512           0
------------------------------------
Tue  9 Jun 17:52:15 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          43         399           0          68         468
Swap:           512         512           0
memory.memsw.limit_in_bytes: 1073741824
memory.memsw.usage_in_bytes: 117428224
memory.limit_in_bytes: 536870912
memory.usage_in_bytes: 117448704
/proc/swaps:
Filename				Type		Size	Used	Priority
none                                    virtual		524288	0	0
/proc/meminfo:
MemTotal:         524288 kB
MemFree:          409408 kB
MemAvailable:     479744 kB
Buffers:               0 kB
Cached:            70336 kB
SwapCached:            0 kB
Active:            39600 kB
Inactive:          50952 kB
Active(anon):      20328 kB
Inactive(anon):      132 kB
Active(file):      19272 kB
Inactive(file):    50820 kB
Unevictable:           0 kB
Mlocked:           75696 kB
SwapTotal:        524288 kB
SwapFree:              0 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:         20352 kB
Mapped:            41448 kB
Shmem:               108 kB
KReclaimable:     124288 kB
Slab:               0 kB
SReclaimable:          0 kB
SUnreclaim:            0 kB
KernelStack:       14700 kB
PageTables:        31928 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6160460 kB
Committed_AS:    7090516 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       96092 kB
VmallocChunk:          0 kB
Percpu:             5920 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      446808 kB
DirectMap2M:     6801408 kB
DirectMap1G:     1048576 kB
              total        used        free      shared  buff/cache   available
Mem:            512          42         400           0          68         469
Swap:           512           0         512
------------------------------------
```

**Comment by brauner** [comment]
@tomponline, try again, please?

**Comment by tomponline** [comment]
@brauner so it looks stable now, however the swap usage calculation isn't right as its showing 100% swap usage when it should be showing 0% (or very close to it).

```
------------------------------------
Tue  9 Jun 19:13:38 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          42         400           0          69         469
Swap:           512         512           0
memory.memsw.limit_in_bytes: 1073741824
memory.usage_in_bytes: 116850688
memory.memsw.usage_in_bytes: 116920320
memory.limit_in_bytes: 536870912
/proc/swaps:
Filename				Type		Size	Used	Priority
none                                    virtual		524288	0	0
/proc/meminfo:
MemTotal:         524288 kB
MemFree:          409924 kB
MemAvailable:     480648 kB
Buffers:               0 kB
Cached:            70724 kB
SwapCached:            0 kB
Active:            35244 kB
Inactive:          55176 kB
Active(anon):      19932 kB
Inactive(anon):        0 kB
Active(file):      15312 kB
Inactive(file):    55176 kB
Unevictable:           0 kB
Mlocked:           75700 kB
SwapTotal:        524288 kB
SwapFree:              0 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:         19848 kB
Mapped:            42108 kB
Shmem:                84 kB
KReclaimable:     119116 kB
Slab:               0 kB
SReclaimable:          0 kB
SUnreclaim:            0 kB
KernelStack:       14988 kB
PageTables:        34132 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6160460 kB
Committed_AS:    7640352 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       96244 kB
VmallocChunk:          0 kB
Percpu:             5040 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      416088 kB
DirectMap2M:     7880704 kB
DirectMap1G:           0 kB
              total        used        free      shared  buff/cache   available
Mem:            512          42         400           0          69         469
Swap:           512         512           0
```

So would expect swap used to be `116920320-116850688=69632 bytes`, although depending on how quickly you read these values, the total swap can go negative.

**Comment by brauner** [comment]
@tomponline, try again, please?

**Comment by tomponline** [comment]
@brauner a lot better, but still getting the odd glitch where the used swap goes to the max limit and then goes back to the expected 0.

```
Tue  9 Jun 19:28:01 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          41         407           0          63         470
Swap:           512         512           0
Tue  9 Jun 19:28:02 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          41         407           0          63         470
Swap:           512           0         512
```

**Comment by tomponline** [comment]
@brauner I've noticed that when reading the cgroup usage values, sometimes if you read the `memory.memsw.usage_in_bytes` then followed, even quickly in a script by `memory.usage_in_bytes` the later can be higher than the former, which is unexpected. I think it may be as memory usage fluctuates it can end up reading the different values at different times sufficiently different to cause used swap to go negative.

**Comment by brauner** [comment]
> @brauner I've noticed that when reading the cgroup usage values, sometimes if you read the `memory.memsw.usage_in_bytes` then followed, even quickly in a script by `memory.usage_in_bytes` the later can be higher than the former, which is unexpected. I think it may be as memory usage fluctuates it can end up reading the different values at different times sufficiently different to cause used swap to go negative.

Yeah, it's a classic problem and one of the fundamental problems of using a filesystem to expose multiple values in different files.

**Comment by tomponline** [comment]
@brauner I guess if it goes negative just set it to zero?

**Comment by brauner** [comment]
> @brauner I guess if it goes negative just set it to zero?



> @brauner I guess if it goes negative just set it to zero?

Yeah, it's a little more tricky. We had that solution before. Try again, please? :)

**Comment by tomponline** [comment]
@brauner I think that has fixed it :)

I've been running it for several minutes on both my local system and the VPS I originally saw the issue on and can't see any problems with it now. Nice one!

**Pull request merged**
