### PR TITLE
Enable ASAN and UBSAN in PR tests

### PR DESCRIPTION
**Pull request by mihalicyn**

### CODE REVIEW

**Comment by mihalicyn** [comment]
So, let's fight with errors first. (-:

**Comment by brauner** [comment]
We've enabled it in LXC a while ago. There's a lot of duct-tape needed usually. ;)

**Comment by stgraber** [comment]
That was surprisingly easy :)

@brauner happy with it?

**Review by brauner — APPROVED** [review]

**Comment by brauner** [comment]
> That was surprisingly easy :)
> 
> @brauner happy with it?

I might've mixed this up with oss-fuzz integration. Which also had some intersection with ubsan/asan.

**Pull request merged**
