### PR TITLE
Removing the empty README file

### PR DESCRIPTION
**Pull request by abbasally5**
- There is already a README.md that is being used

Signed-off-by: Abbas Ally <abbasally5@yahoo.com>

### CODE REVIEW

**Comment by brauner** [comment]
The `README` file is required by autotools. Otherwise they won't compile. :)

**Comment by abbasally5** [comment]
can I add a line to the Makefile such as
README: README.md
and add it to the files to be cleaned?
Sorry for the small change. I a trying to get into open source

**Comment by brauner** [comment]
I'd prefer to just leave it actually. We have this in other autotools based projects as well. It's not a big deal.

**Comment by abbasally5** [comment]
Okay no problem.

**Pull request closed without merging**
