### PR TITLE
proc: Fix /proc/cpuinfo not respecting personality

### PR DESCRIPTION
**Pull request by gibmat**
It was found that the personality within the container was not being properly respected, which for large numbers of CPUs would break reporting of `/proc/cpuinfo` in arm32 containers running on an arm64 host.

Tested on an arm64 QEMU VM; with this fix the 32bit container now properly reports `/proc/cpuinfo`. Shamelessly copied most of the code from the existing `proc_read_with_personality()`.

Fixes: #608.

### CODE REVIEW

**Comment by stgraber** [comment]
@mihalicyn can you take a look?

**Comment by mihalicyn** [comment]
> @mihalicyn can you take a look?

sure! My bad that I've skipped that one.

**Comment by mihalicyn** [comment]
LGTM!

Big thanks for noticing, debugging and fixing, Mathias!

I'll do some refactoring in the following PR.

**Review by mihalicyn — APPROVED** [review]

**Comment by gibmat** [comment]
Would it be possible to merge this in the next few days? I'd like to have the fix included in the Debian 12.2 point release (scheduled for Oct 7). Working back from that date, I need to have the updated package basically ready by the 23rd so there's plenty of time for the update to be approved and included by the release team.

**Review by stgraber — APPROVED** [review]

**Pull request merged**
