### PR TITLE
Fix lxcfs mount handling with newer lxc

### PR DESCRIPTION
**Pull request by stgraber**
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
@hallyn I have uploaded a new lxcfs to Ubuntu with this fix after testing it briefly on an affected wily system.

**Comment by hallyn** [comment]
You are explicitly avoiding cgmanager, should cgmanager.lower also get a special case?

**Comment by stgraber** [comment]
So I thought about it then came to the conclusion that cgmanager.lower should never exist at that point in time.

It's the container post-startup which moves cgmanager to cgmanager.lower before starting cgproxy.

**Comment by hallyn** [comment]
But it is the cgproxy, not lxc, which creates .lower.  It's sort of orthogonal to how lxc feels like running right now.

**Comment by hallyn** [comment]
Thanks.

**Pull request merged**
