### PR TITLE
README: clarify SWAP

### PR DESCRIPTION
**Pull request by stgraber**
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
@brauner anything else I should cover in there?

If not, then we need to make sure that LXCFS behaves as described. Currently in testing, I've noticed that:
 - We don't do the proper SWAP device size when a memory limit is applied
 - We certainly don't have that swappinness logic I've added in there, though I think it would make sense and make the disable-swap knob we have in LXD be more visible

**Comment by brauner** [comment]
> @brauner anything else I should cover in there?
> 
> If not, then we need to make sure that LXCFS behaves as described. Currently in testing, I've noticed that:
> 
> * We don't do the proper SWAP device size when a memory limit is applied

What do you see?

> * We certainly don't have that swappinness logic I've added in there, though I think it would make sense and make the disable-swap knob we have in LXD be more visible

Do we really need more complications in that code? Has anyone asked for this feature? Sure, we can do that but it's one more knob to turn and this doesn't seem to be supported in cgroup2.

**Comment by stgraber** [comment]
Updated the entry to act more as an entry point for anyone missing SWAP in LXCFS.
Also reworded things a bit to not reference swapaccount too much.

**Comment by brauner** [comment]
Thank you!

**Pull request merged**
