### PR TITLE
fix  package name

### PR DESCRIPTION
**Pull request by moweiraul**
fix package name,and add tips.

Signed-off-by: Mowei Jiang   moweiraul@gmail.com

### CODE REVIEW

**Comment by stgraber** [comment]
Thanks!

Can you edit your commit message to include the required `Signed-off-by: Firstname Lastname <email>` line (see CONTRIBUTING.md)?

**Comment by moweiraul** [comment]
> Thanks!
> 
> Can you edit your commit message to include the required `Signed-off-by: Firstname Lastname <email>` line (see CONTRIBUTING.md)?

Signed-off-by: Zhiwei Li cyzz_a102@126.com

> Thanks!
> 
> Can you edit your commit message to include the required `Signed-off-by: Firstname Lastname <email>` line (see CONTRIBUTING.md)?

**Comment by moweiraul** [comment]
> Thanks!
> 
> Can you edit your commit message to include the required `Signed-off-by: Firstname Lastname <email>` line (see CONTRIBUTING.md)?

It has been modified

**Comment by stgraber** [comment]
I see it in the PR description but not the actual commit message.
Anyway, that's sufficient for us and I'll just edit the commit message for you now.

Thanks!

**Pull request merged**
