### PR TITLE
 Revert "bindings: protect do_release_file_info() with mutex"

### PR DESCRIPTION
**Pull request by tomponline**
@brauner I'm still experiencing some lxcfs hangs with this change, so probably best to revert it until I can investigate further.

Thanks

### CODE REVIEW

**Comment by tomponline** [comment]
@Blub @brauner It seems that there is already a mutex protecting the higher functions that call this function anyway:

https://github.com/lxc/lxcfs/blob/8437cc6cb6b424cdb81db35915b7914ef934e736/lxcfs.c#L587-L589

**Comment by tomponline** [comment]
@brauner its quite strange, adding some error logging around the locks seems to fix it, but taking the debug lines starts to introduce hanging again (like its getting stuck on a deadlock).

**Comment by tomponline** [comment]
The `up_users` function just does a temporary lock to incremnt/decrement a counter, doesn't actually lock the actions that happen in the middle.

**Comment by Blub** [comment]
> adding some error logging around the locks seems to fix it

Races are tricky that way. Printing uses syscalls which introduces context switches between kernel and user space, which can affect the timing a *lot*. Any debug helpers you introduce will affect the timing in an unpredictable way. That's what makes race conditions so annoying to hunt.

**Pull request closed without merging**
