### PR TITLE
proc_fuse: cap swap to global values

### PR DESCRIPTION
**Pull request by brauner**
Closes: #412.
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by tomponline** [comment]
@brauner not sure if you are finished with this or not, but as it is, the issue is still occurring:

```
root@test1:~# while :; do date; free -m; sleep 1; done
Tue  9 Jun 11:18:35 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          35         476           0           0         476
Swap:          1024           0        1024
Tue  9 Jun 11:18:36 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          35         476           0           0         476
Swap:          1024           0        1024
Tue  9 Jun 11:18:37 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          35         476           0           0         476
Swap:          1024           0        1024
Tue  9 Jun 11:18:38 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          35         476           0           0         476
Swap:          1024           0        1024
Tue  9 Jun 11:18:39 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          35         476           0           0         476
Swap:          1024           0        1024
Tue  9 Jun 11:18:40 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          35         476           0           0         476
Swap:          1024           0        1024
Tue  9 Jun 11:18:41 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          35         476           0           0         476
Swap:          1024           0        1024
Tue  9 Jun 11:18:42 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          35         476           0           0         476
Swap:          1024 18014398507457540     2025468
Tue  9 Jun 11:18:43 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          35         476           0           0         476
Swap:          1024 18014398507457540     2025468
Tue  9 Jun 11:18:44 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          35         476           0           0         476
Swap:          1024           0        1024
Tue  9 Jun 11:18:45 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          35         476           0           0         476
Swap:          1024           0        1024
```

**Comment by brauner** [comment]
Can you show me
/proc/cmdline
of that system you're seeing that issue on?

**Comment by brauner** [comment]
Oh, and the contents of the container's memory cgroup directory, please

**Comment by tomponline** [comment]
@brauner 

```
BOOT_IMAGE=/boot/vmlinuz-5.4.0-33-generic root=UUID=4f317889-ce82-4d82-9f90-3b5b0dab0925 ro quiet splash intel_iommu=on pci=assign-busses cgroup_enable=memory swapaccount=1 vt.handoff=7
```

**Comment by tomponline** [comment]
@brauner did you want contents of all files?

```
root@test1:/sys/fs/cgroup/memory# ls -la
total 0
drwxrwxr-x  4 nobody root      0 Jun  9 12:06 .
drwxr-xr-x 15 root   root    380 Jun  9 12:06 ..
-rw-r--r--  1 nobody nogroup   0 Jun  9 12:07 cgroup.clone_children
--w--w--w-  1 nobody nogroup   0 Jun  9 12:07 cgroup.event_control
-rw-rw-r--  1 nobody root      0 Jun  9 12:06 cgroup.procs
-rw-r--r--  1 nobody nogroup   0 Jun  9 12:07 memory.failcnt
--w-------  1 nobody nogroup   0 Jun  9 12:07 memory.force_empty
-rw-r--r--  1 nobody nogroup   0 Jun  9 12:07 memory.kmem.failcnt
-rw-r--r--  1 nobody nogroup   0 Jun  9 12:07 memory.kmem.limit_in_bytes
-rw-r--r--  1 nobody nogroup   0 Jun  9 12:07 memory.kmem.max_usage_in_bytes
-r--r--r--  1 nobody nogroup   0 Jun  9 12:07 memory.kmem.slabinfo
-rw-r--r--  1 nobody nogroup   0 Jun  9 12:07 memory.kmem.tcp.failcnt
-rw-r--r--  1 nobody nogroup   0 Jun  9 12:07 memory.kmem.tcp.limit_in_bytes
-rw-r--r--  1 nobody nogroup   0 Jun  9 12:07 memory.kmem.tcp.max_usage_in_bytes
-r--r--r--  1 nobody nogroup   0 Jun  9 12:07 memory.kmem.tcp.usage_in_bytes
-r--r--r--  1 nobody nogroup   0 Jun  9 12:07 memory.kmem.usage_in_bytes
-rw-r--r--  1 nobody nogroup   0 Jun  9 12:06 memory.limit_in_bytes
-rw-r--r--  1 nobody nogroup   0 Jun  9 12:07 memory.max_usage_in_bytes
-rw-r--r--  1 nobody nogroup   0 Jun  9 12:07 memory.memsw.failcnt
-rw-r--r--  1 nobody nogroup   0 Jun  9 12:06 memory.memsw.limit_in_bytes
-rw-r--r--  1 nobody nogroup   0 Jun  9 12:07 memory.memsw.max_usage_in_bytes
-r--r--r--  1 nobody nogroup   0 Jun  9 12:06 memory.memsw.usage_in_bytes
-rw-r--r--  1 nobody nogroup   0 Jun  9 12:07 memory.move_charge_at_immigrate
-r--r--r--  1 nobody nogroup   0 Jun  9 12:07 memory.numa_stat
-rw-r--r--  1 nobody nogroup   0 Jun  9 12:07 memory.oom_control
----------  1 nobody nogroup   0 Jun  9 12:07 memory.pressure_level
-rw-r--r--  1 nobody nogroup   0 Jun  9 12:07 memory.soft_limit_in_bytes
-r--r--r--  1 nobody nogroup   0 Jun  9 12:06 memory.stat
-rw-r--r--  1 nobody nogroup   0 Jun  9 12:07 memory.swappiness
-r--r--r--  1 nobody nogroup   0 Jun  9 12:06 memory.usage_in_bytes
-rw-r--r--  1 nobody nogroup   0 Jun  9 12:06 memory.use_hierarchy
-rw-r--r--  1 nobody nogroup   0 Jun  9 12:07 notify_on_release
drwxr-xr-x 15 root   root      0 Jun  9 12:06 system.slice
-rw-rw-r--  1 nobody root      0 Jun  9 12:06 tasks
drwxr-xr-x  2 root   root      0 Jun  9 12:06 user.slice
```

**Comment by brauner** [comment]
@tomponline, try again.

**Comment by tomponline** [comment]
@brauner seems to be a slightly different issue now, the swap is showing as 100% used (even though this is a brand new idle container only running the `free` command every 1s), so it seems strange that swap usage would spike to 100% then drop down.

```
Tue  9 Jun 12:55:41 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          35         475           0           0         476
Swap:          1024        1024           0
Tue  9 Jun 12:55:42 UTC 2020
              total        used        free      shared  buff/cache   available
Mem:            512          35         475           0           0         476
Swap:          1024           0        1024
```

That being said, perhaps some standard service running on ubuntu 20.04 (and debian 10) is causing memory usage to periodically spike (although actual memory usage is stable at 35M).

**Comment by brauner** [comment]
> @brauner seems to be a slightly different issue now, the swap is showing as 100% used (even though this is a brand new idle container only running the `free` command every 1s), so it seems strange that swap usage would spike to 100% then drop down.
> 
> ```
> Tue  9 Jun 12:55:41 UTC 2020
>               total        used        free      shared  buff/cache   available
> Mem:            512          35         475           0           0         476
> Swap:          1024        1024           0
> Tue  9 Jun 12:55:42 UTC 2020
>               total        used        free      shared  buff/cache   available
> Mem:            512          35         475           0           0         476
> Swap:          1024           0        1024
> ```
> 
> That being said, perhaps some standard service running on ubuntu 20.04 (and debian 10) is causing memory usage to periodically spike (although actual memory usage is stable at 35M).

Now, swap is just notoriously annoying to virtualize.

**Comment by brauner** [comment]
> > @brauner seems to be a slightly different issue now, the swap is showing as 100% used (even though this is a brand new idle container only running the `free` command every 1s), so it seems strange that swap usage would spike to 100% then drop down.
> > ```
> > Tue  9 Jun 12:55:41 UTC 2020
> >               total        used        free      shared  buff/cache   available
> > Mem:            512          35         475           0           0         476
> > Swap:          1024        1024           0
> > Tue  9 Jun 12:55:42 UTC 2020
> >               total        used        free      shared  buff/cache   available
> > Mem:            512          35         475           0           0         476
> > Swap:          1024           0        1024
> > ```
> > 
> > 
> > That being said, perhaps some standard service running on ubuntu 20.04 (and debian 10) is causing memory usage to periodically spike (although actual memory usage is stable at 35M).
> 
> Now, swap is just notoriously annoying to virtualize.

*No

**Pull request merged**
