### PR TITLE
modify the error lib path

### PR DESCRIPTION
**Pull request by elianka**
Signed-off-by: Daniel Kang <kangliang424@gmail.com>

### CODE REVIEW

**Comment by elianka** [comment]
modify the error commit in #198

**Comment by hallyn** [comment]
lxcfs.so in fact ends up in LIBDIR/lxcfs/ does it not?

**Comment by stgraber** [comment]
Yeah, I'm not sure what the problem is here. It's very intentional that liblxcfs isn't in /lib directly but in a subdirectory as it's an internal component of lxcfs which shouldn't be linked against by anyone else.

**Comment by brauner** [comment]
Note also that a while ago I made `liblxcfs` a versionless `libtool` module. So linking against it becomes even more pointless.

**Comment by elianka** [comment]
@hallyn liblxcfs.so is located at LIBDIR not LIBDIR/lxcfs/

**Comment by elianka** [comment]
@stgraber actually, now the liblxcfs.so is not in a subdirectory in /lib. the default path is /usr/local/lib/liblxcfs.so now.

**Comment by elianka** [comment]
@brauner 
this is the tradeoff library path for liblxcfs.so, if we don't set LD_LIBRARY_PATH, we always can not find it. so the fallback dlopen path is usable. 
i have modified it in #198 , meanwhile, i found that the default path is LIBDIR, not LIBDIR/lxcfs. ++

**Comment by brauner** [comment]
But that is caused by compile instructions is it not? The things it that `liblxcfs.so` should stay under a private directory `lxcfs`. This is best practice for `libtool` modules and prevents other programs from trying to link against it.

**Comment by elianka** [comment]
@brauner i fully agree with you about the private directory, meanwhile, it is not now, the default lib path is /usr/local/lib/liblxcfs.so. so maybe a patch should be added.

**Comment by stgraber** [comment]
Right now, our code DOES look at "lxcfs/liblxcfs.so", it's your branch which reverts this very behavior.

Closing this.

**Pull request closed without merging**
